---
runners:
  plugin: threaded
  # number of threads nornir will spin up i.e. 10 devices
  options: 
    num_workers: 10
# Nornir supports different inventories i.e. Ansible/NetBox
inventory:
  plugin: "SimpleInventory"
  # Specifying the full path is possible or just relative path
  options: 
    host_file: "./inventory/hosts.yml"
    group_file: "./inventory/groups.yml"
    defaults_file: "./inventory/defaults.yml"
